### ISSUE TITLE
torchaudio=0.8.0

### ISSUE THREAD

**Issue by oneway234** [SungFeng-Huang/SSL-pretraining-separation#1]
hi, 
I tried to install requirements in anaconda with python=3.7.

But it went wrong.
`ERROR: Could not find a version that satisfies the requirement torchaudio==0.8.0`
`ERROR: No matching distribution found for torchaudio==0.8.0`

Is it must install torchaudio=0.8.0? Or is there any version to replace it?

**Comment by SungFeng-Huang** [comment]
Sorry, it's my typo, it should be 0.7.0.
Just to remember that the versions of torchaudio/torchtext should depend on the pytorch version:
torch | torchaudio | torchtext | python
---|---|---|---
master/nightly | master/nightly | master | >=3.6
1.7.0 | 0.7.0 | 0.8 | >=3.6
1.6.0 | 0.6.0 | 0.7.| >=3.6
1.5.0 | 0.5.0 | 0.6 | >=3.6
1.4.0 | 0.4.0 | 0.5 | ==2.7, >=3.5, <=3.8

Reference:
https://github.com/pytorch/text
https://github.com/pytorch/audio

**Comment by oneway234** [comment]
Thanks for reply!
