### ISSUE TITLE
Weights available?

### ISSUE THREAD

**Issue by jvel07** [SungFeng-Huang/SSL-pretraining-separation#2]
Hi, @SungFeng-Huang! Awesome work, still top 3 SOTA even after two years :)
One question, may I ask for the hugging face link to the final trained models, please? Would be enough with the Libri2Mix `PT-FT ConvTasNet`.

**Comment by SungFeng-Huang** [comment]
@jvel07 Sorry that I didn't upload the models to hugging face, and they were just deleted recently...

**Comment by jvel07** [comment]
@SungFeng-Huang oh, I see. Thanks for your reply! There's no way you have them in your back ups maybe? Or there's no interest on speech separation from your research line anymore?

**Comment by SungFeng-Huang** [comment]
I'm currently focusing on personalized TTS (check out [my repo](https://github.com/SungFeng-Huang/Meta-TTS/tree/refactor)), which would be the topic of my doctoral dissertation (still in progress).

As for speech separation, maybe I'll come back to work on it after graduation (or maybe not), but I'm not planning to deal with it anytime soon.

I can only find 2 back-up models.
The first is a DPTNet trained from scratch [here](https://drive.google.com/drive/folders/115SCzy6CgQ97Fjt3o_16OfQUNsh8-Hqf?usp=share_link), which is requested 2 years ago.
The second was just found in my disk, which is a pretrained (not fine-tuned) Conv-TasNet, but I'm not sure whether it fits the latest code or not. I also upload it [here](https://drive.google.com/drive/folders/1TuAp8B17W4pKX2NFYpwTv2yFZ-wiwRgA?usp=share_link).
Hope these help!

**Comment by jvel07** [comment]
Awesome, the best of luck with your doctoral thesis!
Oh, that's a pity. Thanks anyways! Have a good one :)
